#!/usr/bin/env node
/**
 * The conductor as an MCP server.
 *
 * WHY THIS EXISTS. MCP prompts are surfaced as slash commands by Claude Code, Claude Desktop,
 * VS Code/Copilot, Windsurf and Zed, so the conductor becomes something installed rather than
 * something visited, and it stays current because this reads the live repository rather than a
 * bundled copy. The folder under conductor/ is the other install path, for agents that load
 * SKILL.md.
 *
 * WHAT IT SERVES. The conductor itself as the prompt `conductor` (SKILL.md without its front
 * matter), and every guidance and template file as a further prompt, so a client with a small
 * context window can load one file at a time as SKILL.md directs. The same files are also
 * resources (conductor://SKILL.md, conductor://guidance/planning.md) for clients that read
 * resources rather than prompts.
 *
 * WHY IT FETCHES INSTEAD OF BUNDLING. A bundled snapshot is a second copy of the truth, and a
 * second copy is a thing that will disagree with the first and then be trusted anyway. The
 * index and the files are read from the repository at startup, so a change merged an hour ago
 * is available without anyone republishing anything.
 *
 * WHY ONE HOST. Both the index (library.json, generated by scripts/emit.py) and the files come
 * from the repository, so the server needs GitHub alone to start. JULES_PROMPTS_INDEX can point
 * at a prompts.json instead, which lists the same files.
 *
 * OR FROM A COPY ON DISK, WITH NO NETWORK AT ALL. Private and offline projects cannot, or must
 * not, reach GitHub, and a request for a file is itself a small signal of what someone is
 * working on. JULES_PROMPTS_DIR=/path/to/a/clone reads the index and every file from that
 * directory. In that mode the global fetch is replaced with one that throws, so no later change
 * to this file can quietly reach the network; the smoke test runs this mode in CI.
 *
 * FAILURE IS LOUD, DELIBERATELY. If the fetch fails this exits non-zero with the reason rather
 * than starting and serving an empty list. A server that connects and offers nothing looks
 * identical to a client misconfiguration, and the person debugging it would have no way to
 * tell which they were looking at.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

const REPO = process.env.JULES_PROMPTS_REPO || "melbinjp/jules-prompts";
const REF = process.env.JULES_PROMPTS_REF || "main";
const RAW = `https://raw.githubusercontent.com/${REPO}/${REF}`;
const INDEX = process.env.JULES_PROMPTS_INDEX || `${RAW}/library.json`;
const LOCAL = process.env.JULES_PROMPTS_DIR ? path.resolve(process.env.JULES_PROMPTS_DIR) : null;
const SOURCE = LOCAL ? `${LOCAL} (local copy, no network)` : `${REPO}@${REF}`;
const VERSION = "2.0.0";

if (LOCAL) {
  globalThis.fetch = () => {
    throw new Error("local mode (JULES_PROMPTS_DIR) must not use the network");
  };
}

async function getJson(url) {
  if (LOCAL) return JSON.parse(await readFile(path.join(LOCAL, "library.json"), "utf8"));
  const r = await fetch(url, { headers: { "User-Agent": "jules-prompts-mcp" } });
  if (!r.ok) throw new Error(`${url} returned ${r.status}`);
  return r.json();
}

async function getText(url) {
  const r = await fetch(url, { headers: { "User-Agent": "jules-prompts-mcp" } });
  if (!r.ok) throw new Error(`${url} returned ${r.status}`);
  return r.text();
}

/** Split YAML front matter from the body. The body is what an agent is given; the front matter
 *  is metadata for skill loaders and would only repeat the description. */
function splitFrontMatter(text) {
  if (!text.startsWith("---")) return text;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return text;
  return text.slice(end + 4).replace(/^\n+/, "");
}

/** The files an index lists, as {name, title, description, category, path}. library.json lists
 *  `files`; the site's prompts.json lists `prompts`. Either is accepted. */
function entriesOf(index) {
  if (Array.isArray(index.files)) {
    return index.files.map((f) => ({
      name: f.name,
      title: f.title,
      description: f.description,
      category: f.kind,
      path: f.path,
    }));
  }
  return (index.prompts || []).map((p) => ({
    name: p.slug,
    title: p.title,
    description: p.description,
    category: (p.category || "").toLowerCase(),
    path: p.source_path,
  }));
}

async function main() {
  const index = await getJson(INDEX);
  const entries = entriesOf(index);
  if (entries.length === 0) throw new Error(`${INDEX} listed no files`);

  const loaded = await Promise.all(
    entries.map(async (e) => {
      const text = LOCAL
        ? await readFile(path.join(LOCAL, e.path), "utf8")
        : await getText(`${RAW}/${e.path}`);
      return { ...e, body: splitFrontMatter(text), uri: `conductor://${e.path.replace(/^conductor\//, "")}` };
    }),
  );

  const server = new McpServer({ name: "jules-prompts", version: VERSION });

  for (const f of loaded) {
    server.registerPrompt(
      f.name,
      {
        title: f.title,
        description: f.category ? `[${f.category}] ${f.description}` : f.description,
      },
      () => ({ messages: [{ role: "user", content: { type: "text", text: f.body } }] }),
    );
    server.registerResource(
      f.name,
      f.uri,
      { title: f.title, description: f.description, mimeType: "text/markdown" },
      async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/markdown", text: f.body }] }),
    );
  }

  // Coverage on stderr, where it does not corrupt the stdio protocol. A server that says how
  // many files it loaded can be told apart from one that loaded none and connected anyway.
  process.stderr.write(
    `jules-prompts: ${loaded.length} file(s) of the conductor from ${SOURCE}, ` +
      `served as prompts and resources, kinds: ${[...new Set(loaded.map((f) => f.category))].sort().join(", ")}\n`,
  );

  await server.connect(new StdioServerTransport());
}

main().catch((e) => {
  process.stderr.write(`jules-prompts: failed to start: ${e.message}\n`);
  process.exit(1);
});
